import type { Category, Lang, WordPair } from "./types";

type Raw = Record<Category, readonly (readonly [string, string])[]>;

const FR: Raw = {
  everyday: [
    ["Chat", "Chien"],
    ["Café", "Thé"],
    ["Lit", "Canapé"],
    ["Fenêtre", "Porte"],
    ["Téléphone", "Tablette"],
    ["Lunettes", "Lentilles"],
    ["Chapeau", "Casquette"],
    ["Manteau", "Veste"],
    ["Savon", "Shampoing"],
    ["Oreiller", "Coussin"],
    ["Réveil", "Horloge"],
    ["Serviette", "Torchon"],
    ["Tapis", "Moquette"],
    ["Brosse", "Peigne"],
    ["Parapluie", "Imperméable"],
  ],
  food: [
    ["Pizza", "Tarte"],
    ["Croissant", "Pain au chocolat"],
    ["Fromage", "Beurre"],
    ["Chocolat", "Caramel"],
    ["Frites", "Chips"],
    ["Soupe", "Potage"],
    ["Steak", "Hamburger"],
    ["Sushi", "Maki"],
    ["Glace", "Sorbet"],
    ["Vin", "Champagne"],
    ["Bière", "Cidre"],
    ["Pâtes", "Riz"],
    ["Pomme", "Poire"],
    ["Citron", "Orange"],
    ["Yaourt", "Fromage blanc"],
  ],
  places: [
    ["Plage", "Piscine"],
    ["Montagne", "Colline"],
    ["Forêt", "Jungle"],
    ["Ville", "Village"],
    ["École", "Université"],
    ["Hôpital", "Clinique"],
    ["Restaurant", "Café"],
    ["Cinéma", "Théâtre"],
    ["Musée", "Galerie"],
    ["Aéroport", "Gare"],
    ["Hôtel", "Auberge"],
    ["Bibliothèque", "Librairie"],
    ["Parc", "Jardin"],
    ["Église", "Cathédrale"],
    ["Supermarché", "Marché"],
  ],
  nature: [
    ["Lune", "Soleil"],
    ["Étoile", "Planète"],
    ["Rivière", "Lac"],
    ["Océan", "Mer"],
    ["Fleur", "Plante"],
    ["Arbre", "Buisson"],
    ["Rose", "Tulipe"],
    ["Nuage", "Brouillard"],
    ["Pluie", "Neige"],
    ["Vent", "Tempête"],
    ["Volcan", "Montagne"],
    ["Île", "Presqu'île"],
    ["Désert", "Savane"],
    ["Papillon", "Abeille"],
    ["Loup", "Renard"],
  ],
  objects: [
    ["Stylo", "Crayon"],
    ["Livre", "Cahier"],
    ["Ciseaux", "Cutter"],
    ["Marteau", "Maillet"],
    ["Clé", "Cadenas"],
    ["Bouteille", "Carafe"],
    ["Verre", "Tasse"],
    ["Assiette", "Bol"],
    ["Fourchette", "Cuillère"],
    ["Lampe", "Bougie"],
    ["Miroir", "Vitre"],
    ["Sac", "Valise"],
    ["Vélo", "Trottinette"],
    ["Voiture", "Camion"],
    ["Avion", "Hélicoptère"],
    ["Bateau", "Voilier"],
    ["Train", "Métro"],
    ["Piano", "Clavier"],
    ["Guitare", "Ukulélé"],
    ["Télévision", "Ordinateur"],
  ],
  culture: [
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Ski", "Snowboard"],
    ["Danse", "Gymnastique"],
    ["Roman", "Nouvelle"],
    ["Film", "Série"],
    ["Chanson", "Mélodie"],
    ["Photo", "Peinture"],
    ["Pirate", "Viking"],
    ["Magicien", "Sorcier"],
    ["Vampire", "Loup-garou"],
    ["Roi", "Empereur"],
    ["Château", "Palais"],
    ["Dragon", "Dinosaure"],
    ["Super-héros", "Vilain"],
  ],
  manga: [
    ["Naruto", "Sasuke"],
    ["Goku", "Vegeta"],
    ["Luffy", "Zoro"],
    ["Pikachu", "Évoli"],
    ["Totoro", "Chihiro"],
    ["Tanjiro", "Nezuko"],
    ["Eren", "Lévi"],
    ["Light", "L"],
    ["Gon", "Killua"],
    ["Saitama", "Genos"],
    ["Ninja", "Samouraï"],
    ["Mecha", "Kaiju"],
    ["Manga", "Anime"],
    ["Pokémon", "Digimon"],
    ["Shonen", "Seinen"],
  ],
};

const EN: Raw = {
  everyday: [
    ["Cat", "Dog"],
    ["Coffee", "Tea"],
    ["Bed", "Sofa"],
    ["Window", "Door"],
    ["Phone", "Tablet"],
    ["Glasses", "Contacts"],
    ["Hat", "Cap"],
    ["Coat", "Jacket"],
    ["Soap", "Shampoo"],
    ["Pillow", "Cushion"],
    ["Alarm", "Clock"],
    ["Towel", "Rag"],
    ["Rug", "Carpet"],
    ["Brush", "Comb"],
    ["Umbrella", "Raincoat"],
  ],
  food: [
    ["Pizza", "Pie"],
    ["Croissant", "Muffin"],
    ["Cheese", "Butter"],
    ["Chocolate", "Caramel"],
    ["Fries", "Chips"],
    ["Soup", "Stew"],
    ["Steak", "Burger"],
    ["Sushi", "Sashimi"],
    ["Ice cream", "Sorbet"],
    ["Wine", "Champagne"],
    ["Beer", "Cider"],
    ["Pasta", "Rice"],
    ["Apple", "Pear"],
    ["Lemon", "Orange"],
    ["Yogurt", "Cream"],
  ],
  places: [
    ["Beach", "Pool"],
    ["Mountain", "Hill"],
    ["Forest", "Jungle"],
    ["City", "Village"],
    ["School", "University"],
    ["Hospital", "Clinic"],
    ["Restaurant", "Cafe"],
    ["Cinema", "Theatre"],
    ["Museum", "Gallery"],
    ["Airport", "Station"],
    ["Hotel", "Inn"],
    ["Library", "Bookstore"],
    ["Park", "Garden"],
    ["Church", "Cathedral"],
    ["Supermarket", "Market"],
  ],
  nature: [
    ["Moon", "Sun"],
    ["Star", "Planet"],
    ["River", "Lake"],
    ["Ocean", "Sea"],
    ["Flower", "Plant"],
    ["Tree", "Bush"],
    ["Rose", "Tulip"],
    ["Cloud", "Fog"],
    ["Rain", "Snow"],
    ["Wind", "Storm"],
    ["Volcano", "Mountain"],
    ["Island", "Peninsula"],
    ["Desert", "Savanna"],
    ["Butterfly", "Bee"],
    ["Wolf", "Fox"],
  ],
  objects: [
    ["Pen", "Pencil"],
    ["Book", "Notebook"],
    ["Scissors", "Cutter"],
    ["Hammer", "Mallet"],
    ["Key", "Padlock"],
    ["Bottle", "Jug"],
    ["Glass", "Mug"],
    ["Plate", "Bowl"],
    ["Fork", "Spoon"],
    ["Lamp", "Candle"],
    ["Mirror", "Window"],
    ["Bag", "Suitcase"],
    ["Bike", "Scooter"],
    ["Car", "Truck"],
    ["Plane", "Helicopter"],
    ["Boat", "Sailboat"],
    ["Train", "Subway"],
    ["Piano", "Keyboard"],
    ["Guitar", "Ukulele"],
    ["Television", "Computer"],
  ],
  culture: [
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Ski", "Snowboard"],
    ["Dance", "Gymnastics"],
    ["Novel", "Short story"],
    ["Movie", "Series"],
    ["Song", "Melody"],
    ["Photo", "Painting"],
    ["Pirate", "Viking"],
    ["Magician", "Wizard"],
    ["Vampire", "Werewolf"],
    ["King", "Emperor"],
    ["Castle", "Palace"],
    ["Dragon", "Dinosaur"],
    ["Superhero", "Villain"],
  ],
  manga: [
    ["Naruto", "Sasuke"],
    ["Goku", "Vegeta"],
    ["Luffy", "Zoro"],
    ["Pikachu", "Eevee"],
    ["Totoro", "Chihiro"],
    ["Tanjiro", "Nezuko"],
    ["Eren", "Levi"],
    ["Light", "L"],
    ["Gon", "Killua"],
    ["Saitama", "Genos"],
    ["Ninja", "Samurai"],
    ["Mecha", "Kaiju"],
    ["Manga", "Anime"],
    ["Pokemon", "Digimon"],
    ["Shonen", "Seinen"],
  ],
};

function flatten(lang: Lang, raw: Raw): WordPair[] {
  const out: WordPair[] = [];
  for (const [category, pairs] of Object.entries(raw) as [
    Category,
    Raw[Category],
  ][]) {
    pairs.forEach(([civilian, undercover], i) => {
      out.push({
        id: `${lang}-${category}-${i}`,
        civilian,
        undercover,
        category,
      });
    });
  }
  return out;
}

export const WORDS: Record<Lang, WordPair[]> = {
  fr: flatten("fr", FR),
  en: flatten("en", EN),
};

export function pairsFor(
  lang: Lang,
  categories: Category[],
  usedIds: string[],
): WordPair[] {
  const set = new Set(categories);
  const all = WORDS[lang].filter((p) => set.has(p.category));
  const fresh = all.filter((p) => !usedIds.includes(p.id));
  return fresh.length > 0 ? fresh : all;
}

export function pickPair(
  lang: Lang,
  categories: Category[],
  usedIds: string[],
): WordPair | null {
  const pool = pairsFor(lang, categories, usedIds);
  if (pool.length === 0) return null;
  return pool[Math.floor(Math.random() * pool.length)] ?? null;
}


